#!/bin/bash -e

readonly SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
readonly BASE_DIR=$(dirname -- "$SCRIPT_DIR")
readonly COMMAND=$(basename -- "${BASH_SOURCE[0]}")

if [ "$COMMAND" == "binstub" ]; then
  echo "ERROR: don't run binstub directly" >&2
  exit 1
fi

cd $BASE_DIR

if [ "$COMMAND" == "up" ] && [ $# -eq 0 ]; then
  docker compose $COMMAND -d
else
  docker compose $COMMAND "$@"
fi
